#adapted from https://medium.com/@fbzga/how-to-cache-bundle-install-with-docker-7bed453a5800

app:
  build: .
  command: ./start
  volumes:
    - .:/app
  volumes_from:
    - box

box:
  image: busybox
  volumes:
    - /box
